### ISSUE TITLE
Use string format instead uf prefix/suffix

### ISSUE THREAD

**Issue by micheljung** [curioustechizen/android-ago#15]
Prefix/suffix is not locale friendly, using a String format instead would solve that problem.

**Comment by curioustechizen** [comment]
Agreed. I'll explore ways to incorporate this feedback. 

What comes to the top of my mind is an overloaded version of the `setReferenceTime` method that takes a format String and a `varargs` as parameters. However it might make sense to allow setting the format using an attribute too.

**Comment by curioustechizen** [comment]
Fixed in v1.4.0. While it is not explicitly using  `String.format`, it does deprecate `prefix` and `suffix` in favor of a more general hook to customize the text before display.
