### ISSUE TITLE
Frequent IndexOutOfBoundsException

### ISSUE THREAD

**Issue by pankajbatra** [curioustechizen/android-ago#23]
Fatal Exception: java.lang.IndexOutOfBoundsException
Invalid index 1, size is 1
java.util.ArrayList.throwIndexOutOfBoundsException (ArrayList.java:251)
java.util.ArrayList.get (ArrayList.java:304)
android.widget.TextView.sendAfterTextChanged (TextView.java:7119)
android.widget.TextView.setText (TextView.java:3574)
android.widget.TextView.setText (TextView.java:3425)
android.widget.TextView.setText (TextView.java:3400)
com.github.curioustechizen.ago.RelativeTimeTextView.updateTextDisplay (RelativeTimeTextView.java:146)
com.github.curioustechizen.ago.RelativeTimeTextView.access$200 (RelativeTimeTextView.java:22)
com.github.curioustechizen.ago.RelativeTimeTextView$UpdateTimeRunnable.run (RelativeTimeTextView.java:265)

**Comment by curioustechizen** [comment]
@pankajbatra Is it possible to provide a test case that reproduces the issue?

**Comment by pankajbatra** [comment]
We are using textview on ItemViewHolder to show live orders.
There are 2 states of order dispatched and delivered.
As soon as an order is marked as delivered it moves from dispatched to delivered fragment.
Issue may be that RelativeTimeTextView thread tries to update time on a textview which does not exists anymore.

**Comment by curioustechizen** [comment]
@pankajbatra Thanks for the explanation. However, I don't think that what you are suspecting is causing the issue. Here are a few things that come to mind.

1. Looking at the stack trace, in particular this line:

```
android.widget.TextView.sendAfterTextChanged (TextView.java:7119)
```

If I remember correctly, this implies that you have a `TextWatcher` set on the `TextView`. Can you confirm if this is the case? `RelativeTimeTextView` was not originally meant to be an `Editable` so this might cause issues.

2. The other angle to debug is to replace your `RelativeTimeTextView`s with regular `TextView`s and see if the issue still occurs.

**Comment by pankajbatra** [comment]
Yes, we have TextWatcher set on Textview.
As of now, I have replaced it with regular TextView and using android util method to show relative time.
