### ISSUE TITLE
setReferenceTime get "0 time ago"

### ISSUE THREAD

**Issue by archiecrown** [curioustechizen/android-ago#24]
When I set mReferenceTime lower than currentTimeMillis method getRelativeTimeDisplayString returned "0 time ago"
For example: I have mReferenceTime = 10, and currentTimeMillis = 8. Method getRelativeTimeDisplayString will be return "0 time ago"

Any ideas?

**Comment by curioustechizen** [comment]
This does not seem right. If mReferenceTime < currentTimeMillis, we display "x minutes ago" etc, else we display "in x minutes" etc.

Can you provide a reproducible test case?

**Comment by archiecrown** [comment]
I use this TextView in my chat. When I receive message with mReferenceTime greaten then currentTimeMillis method getRelativeTimeDisplayString returned "0 time ago". It's synchronized time problem on device.

But I found simple solution

textView.setReferenceTime(Math.min(System.currentTimeMillis(), mReferenceTime));

This solved my problem

**Comment by curioustechizen** [comment]
@archiecrown Ah I see. So I'll close this issue now.
