### ISSUE TITLE
Publish to maven central

### ISSUE THREAD

**Issue by curioustechizen** [curioustechizen/android-ago#3]

**Comment by pankajbatra** [comment]
Please publish it soon!

**Comment by curioustechizen** [comment]
I took a stab at this yesterday (I have created a group in maven central) and generated the AAR. However, uploading it didn't work as expected since it requires me to sign the artifacts using GPG keys (or something like that). I'm a complete Maven newbie so it may take some time for me to sort it our.

I'll revisit this soon, but in the meanwhile, you can tell gradle to **directly depend on the github repo** itself!

See [this fork](https://github.com/macksuelsantos/android-ago) of this repo to see how this can be done.

**Comment by pankajbatra** [comment]
Thanks Kiran.
