### ISSUE TITLE
Add support for reference time in future.

### ISSUE THREAD

**Issue by Giorgi** [curioustechizen/android-ago#4]
It would be nice if it supported future reference times as well.

**Comment by niharikasah** [comment]
@curioustechizen its not showing tomorrow instead shows number of hours, for instance if date in 29/3/2018 at 3:40pm and today is 28/3/2018 2:40pm, the text rendered is in 23 hrs instead of tomorrow. Can you please verify this?

**Comment by curioustechizen** [comment]
@niharikasah If I remember correctly, if the date is more than 24 hours in the future, it shows as "tomorrow". You can see this in [the sample](https://github.com/curioustechizen/android-ago/blob/e7e9f92b99af295acff49fd4056026ff9341b308/android-ago-sample/src/com/github/curioustechizen/ago/sample/DummyContent.java#L29). 
This is a feature of the `DateUtils` API that is used by this library.
