### ISSUE TITLE
A String Completed added prior to time

### ISSUE THREAD

**Issue by visherandro** [curioustechizen/android-ago#43]
there is a Completed added to the time like Completed 5 hrs.ago how is that even possible and in another activity there is no problem

**Comment by talk2cerlin** [comment]
Check your xml for `app:relative_time_prefix="Completed "` and remove that

**Comment by myroniak** [comment]
Thanks!

**Comment by curioustechizen** [comment]
@visherandro I'm closing this issue for now. If you are still facing problems feel free to reopen
