### ISSUE TITLE
Locale

### ISSUE THREAD

**Issue by abdulmalekDery** [curioustechizen/android-ago#52]
Is this library available in other languages?
if not are you planning to add this feature in the near future

note: I can help translate into Arabic

**Comment by curioustechizen** [comment]
@abdulmalekDery Yes, it is. Most of the display strings come directly from https://developer.android.com/reference/android/text/format/DateUtils.html#getRelativeTimeSpanString(long, long, long, int) which is provided by Android.

This library adds only one string: "Just now". Translations for this are provided using regular Android resources mechanism. [Here](https://github.com/curioustechizen/android-ago/tree/master/android-ago/res) is a list of languages for which it is present. I see Arabic is already in there :) but thanks for volunteering.
