### ISSUE TITLE
Time is one hour behind on old Galaxy Tab 3 using Android 4.4.2

### ISSUE THREAD

**Issue by erikswed** [curioustechizen/android-ago#53]
HI and thanks for grate lib.
Using 'com.github.curioustechizen.android-ago:library:1.3.4' and XML looks like:

```
     <com.github.curioustechizen.ago.RelativeTimeTextView
                android:id="@+id/timestamp"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_marginEnd="2dp"
                android:layout_marginRight="2dp"
                tools:text="Just Now"/>
```
The time is always one hour behind. The device clock is set correctly. 
I am in Sweden btw. What do you think? In Sweden we have summer time adjustment that mean during summer time is set forward one hour. It feels like your lib dont take that into consideration since the time I see on the Galaxy tab 3 is normal European time(correct time) (but it will for me in Sweden be one our behind)( We do this time thing to get more daylight sunlight)
https://www.timeanddate.com/time/change/sweden/malmo

I have also a Galaxy Note 4 running android 6.0.1 and time is correct all ok

**Comment by curioustechizen** [comment]
@erikswed The library does not calculate the time, we just use [DateUtils](https://developer.android.com/reference/android/text/format/DateUtils.html). Could you try creating a simple app using `getRelativeTimeSpanString(long, long, long, int)` from that class and see what it prints?

**Comment by curioustechizen** [comment]
@erikswed Have you gotten a chance to try out the DateUtils class yet?

**Comment by erikswed** [comment]
Hmm
I cant figure this out right away very strange. I do as you say creating a test project here is the code

```
        Long mReferenceTime = 1509262481035L; // 14 minutes ago
        RelativeTimeTextView timestampView1 = findViewById(R.id.timestamp1);
        TextView timestampView2 = findViewById(R.id.timestamp2);

        timestampView1.setReferenceTime(mReferenceTime);
        long now = System.currentTimeMillis();
        long difference = now - mReferenceTime;

        timestampView2.setText(DateUtils.getRelativeTimeSpanString(mReferenceTime,
                now,
                DateUtils.MINUTE_IN_MILLIS,
                DateUtils.FORMAT_ABBREV_RELATIVE));
```

The `timestamp1` and `timestamp2` show the same mReferenceTime and on Api23 time is correct but on the Galaxy Tab 3 using Android 4.4.2 time is one hour behind.
There´s is something obvious going on must google this more.. what you think
