### ISSUE TITLE
this work fine in recyclerviews?

### ISSUE THREAD

**Issue by webserveis** [curioustechizen/android-ago#55]
If you have 1000 items in a recyclerview, running 1000 threads every time?
Or it detects when the item is not displayed and thus ends its thread of execution

**Comment by curioustechizen** [comment]
@webserveis Yes it is safe to use in RecyclerViews. This library does not use threads at all. It simply uses `Runnable`s as a way to tell a `Handler` what to do when the time changes.

The number of scheduled handlers is slightly more than the number of recyclerview items on screen. Once a `View` is no longer visible, the callback for its [handler is removed](https://github.com/curioustechizen/android-ago/blob/c7b75e5780e20fec80a8963f41edbbb626d55818/android-ago/src/com/github/curioustechizen/ago/RelativeTimeTextView.java#L198).
